import {
  Activity,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  Braces,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  CircleHelp,
  CircleX,
  Code2,
  Compass,
  Cpu,
  Database,
  FileSearch,
  FileText,
  FlaskConical,
  GitBranch,
  LayoutDashboard,
  Lock,
  Network,
  NotebookPen,
  PackageCheck,
  Play,
  Rocket,
  Send,
  Settings2,
  SlidersHorizontal,
  Sparkles,
  Terminal,
  TextCursorInput,
  Trophy,
  Upload,
  User,
  Video,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  account_tree: GitBranch,
  analytics: Activity,
  arrow_forward: GitBranch,
  auto_awesome: Sparkles,
  bar_chart: BarChart3,
  biotech: FlaskConical,
  calendar_today: CalendarDays,
  cancel: CircleX,
  check: Check,
  check_circle: CheckCircle2,
  code: Code2,
  code_blocks: Braces,
  dashboard: LayoutDashboard,
  database: Database,
  deployed_code: PackageCheck,
  edit_note: NotebookPen,
  electric_bolt: Zap,
  emoji_events: Trophy,
  explore: Compass,
  find_in_page: FileSearch,
  insights: ChartNoAxesCombined,
  lock: Lock,
  memory: Cpu,
  military_tech: Trophy,
  model_training: BrainCircuit,
  person: User,
  play_arrow: Play,
  psychology: Brain,
  publish: Upload,
  published_with_changes: GitBranch,
  query_stats: BarChart3,
  quiz: CircleHelp,
  schema: Network,
  send: Send,
  settings_input_component: SlidersHorizontal,
  settings_suggest: Settings2,
  smart_display: Video,
  smart_toy: Bot,
  terminal: Terminal,
  text_fields: TextCursorInput,
  transform: Workflow,
  verified: BadgeCheck,
  article: FileText,
  menu_book: BookOpen,
  rocket: Rocket,
};

interface AppIconProps {
  name: string;
  className?: string;
  strokeWidth?: number;
}

export function AppIcon({ name, className, strokeWidth = 1.75 }: AppIconProps) {
  const Icon = iconMap[name] ?? CircleHelp;
  return <Icon aria-hidden="true" className={className} strokeWidth={strokeWidth} />;
}
